main:
  params: [args]
  steps:
  - before:
      assign:
      - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - region: ${sys.get_env("GOOGLE_CLOUD_LOCATION")}
  - sleep:
      call: sys.sleep
      args:
        seconds: ${60 * 60 * 7}
  - morningAIBot:
      try:
        steps:
        - exec:
            call: http.get
            args:
              url: ${"https://" + region + "-" + project + ".cloudfunctions.net/morning-ai-bot"}
              auth:
                type: OIDC
      retry:
        predicate: ${retryPredicate}
        max_retries: 5
        backoff:
          initial_delay: 30
          max_delay: 60
          multiplier: 2
  - after:
      call: http.get
      args:
        url: ${args.url}
        auth:
          type: OAuth2

retryPredicate:
  params: [e]
  steps:
    - serverError:
        switch:
        - condition: ${500 <= e.code and e.code < 600}
          return: True
    - else:
        return: False

