main:
  params: [args]
  steps:
  - before:
      assign:
      - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
      - region: ${sys.get_env("GOOGLE_CLOUD_LOCATION")}
  - sleep:
      call: sys.sleep
      args:
        seconds: ${60 * 60 * 9}
  - millionCelebrationLoad:
      try:
        steps:
        - upload:
            call: http.get
            args:
              url: ${"https://" + region + "-" + project + ".cloudfunctions.net/million-celebration-load"}
              auth:
                type: OIDC
      retry:
        predicate: ${retryPredicate}
        max_retries: 2
        backoff:
          initial_delay: ${60 * 10}
          max_delay: ${60 * 30}
          multiplier: 2
  - millionCelebrationTweet:
      try:
        steps:
        - tweet:
            call: http.get
            args:
              url: ${"https://" + region + "-" + project + ".cloudfunctions.net/million-celebration-tweet"}
              auth:
                type: OIDC
      retry:
        predicate: ${retryPredicate}
        max_retries: 2
        backoff:
          initial_delay: ${60 * 10}
          max_delay: ${60 * 30}
          multiplier: 2
  - after:
      call: http.get
      args:
        url: ${args.url}
        auth:
          type: OAuth2

retryPredicate:
  params: [e]
  steps:
    - serverError:
        switch:
        - condition: ${500 <= e.code and e.code < 600}
          return: True
    - else:
        return: False
